### ISSUE TITLE
Graag ook 'onbekend' toevoegen in de codelijst bemonsteringsinstrument

### ISSUE THREAD

**Issue by ChandraAlgoe** [bodemenondergrond/codelijst-bemonsteringsinstrument#1]
In de codelijst bemonsteringsinstrument ontbreekt nog 'onbekend'.
Het veld bemonsteringsinstrument is verplicht in te vullen.
Voor de archief data in de DOV-databank is het soms niet mogelijk deze informatie te achterhalen en kunnen we dit veld niet anders invullen dan met 'onbekend'

**Comment by dluts** [comment]
+1

**Comment by ChandraAlgoe** [comment]
We voorzien datamigratie zodat de code 'onbekend' op dit moment niet nodig is

**Comment by timothy-debock** [comment]
er wordt voor boring gekozen ipv onbekend
