### ISSUE TITLE
Graag 2 afkortingen weglaten uit de codelijst

### ISSUE THREAD

**Issue by ChandraAlgoe** [bodemenondergrond/codelijst-bemonsteringsinstrument#3]
(AS) weglaten bij Avegaarboor

![image](https://github.com/bodemenondergrond/codelijst-bemonsteringsinstrument/assets/48786550/131b203e-72ce-4f61-9b0e-62692aa77dba)

(HSAS) weglaten bij Holle avegaarboor
![image](https://github.com/bodemenondergrond/codelijst-bemonsteringsinstrument/assets/48786550/9a9b902c-0e1e-4d6a-a1ac-509e89d96701)

**Comment by timothy-debock** [comment]
textuele aanpassing aan initiele codelijst lijkt me ok te zijn
Dit wordt verwerkt in de volgende versie

**Comment by timothy-debock** [comment]
v0.1.1
