### ISSUE TITLE
Een aanpassing bij Dikwandige steekbus

### ISSUE THREAD

**Issue by ChandraAlgoe** [bodemenondergrond/codelijst-bemonsteringsinstrument#4]
Onder Dikwandige steekbus staat er -- -- Dikwandig steekbus - geslagen (OS-T/W-PE)
dit moet zijn
Dikwandig**e** steekbus - geslagen (OS-T**K**/W-PE)

![image](https://github.com/bodemenondergrond/codelijst-bemonsteringsinstrument/assets/48786550/0462f170-7a20-4cbe-b0d9-66c212d900cd)

**Comment by timothy-debock** [comment]
aangepast
