### ISSUE TITLE
Correcties in schrijfwijze: Rollenbeitel en Edelman boor

### ISSUE THREAD

**Issue by ChandraAlgoe** [bodemenondergrond/codelijst-bemonsteringsinstrument#5]
Rollenbeitel ipv Rollebeitel
![image](https://github.com/bodemenondergrond/codelijst-bemonsteringsinstrument/assets/48786550/5f88efea-9fda-4674-8249-2b4f28dbe086)

Edelman boor ipv Edelmanboor
![image](https://github.com/bodemenondergrond/codelijst-bemonsteringsinstrument/assets/48786550/419fe2ea-e068-4e82-9811-95a497a4516d)

**Comment by JulesVMM** [comment]
Even ter aanvulling in de discussie:

Taalkundig gezien moet 'Edelmanboor' een enkel woord zijn, gezien een eigennaam met een ander woord beschouwd wordt als een gewone samenstelling.

https://www.vlaanderen.be/team-taaladvies/spellingregels/aaneenschrijven/aaneenschrijven-05-combinaties-met-eigennamen

**Comment by dluts** [comment]
Pragmastisch zouden we vanuit bodem willen gaan voor het taalkunding niet correcte 'Edelman boor'.

Het is bij DOV (binnen de bodemobjecten) al in gebruik in de codelijst van de 'parameter' 'Bemonstering bodem instrument' onder de vorm 'Edelman boor'. 
![image](https://github.com/bodemenondergrond/codelijst-bemonsteringsinstrument/assets/51995549/c2cf2d8a-5601-4552-b9eb-75c94b316760)

Deze codelijst zou bij de migratie van de bodemmonsters en observaties naar de nieuwe monsters en observaties, migreren naar de het bemonsteringsinstrument attribuut en de bij behorende codelijst.
Omdat 'Edelman boor' binnen DOV op dit moment al gebruikt wordt en het ook al onderdeel is van geautomatiseerde uitwisseling tussen DOV en externe partners (in het kader van Cmon). Stellen we voor om vanwege pragmatische redenen voor 'Edelman boor' te gebruiken voor deze codelijst. Dit beperkt de wijzigingen bij de migratie en disruptie van andere processen tot het minimum.

Daarnaast zou ik voorstellen om 'Edelmanboor' als alternatieve naam toe te voegen door 'altlabel' te gebruiken.

**Comment by jasper-verhaegen** [comment]
‘Edelmanboor’ weet ik niet maar ‘Edelmanboring’ komt wel voor als boormethode. 

Zowel ‘Edelmanboor’ als ‘Edelman boor’ komen online voor maar het is dan vaker ‘Edelman grondboor’ als het uiteen geschreven is.
‘Edelmanboor’ lijkt vaker voor te komen.

Volgens de taalregels lijkt mij ‘Edelmanboor’ de correcte schrijfwijze te zijn: [https://www.vlaanderen.be/team-taaladvies/spellingregels/aaneenschrijven/aaneenschrijven-01-hoofdregels-los-of-aaneen-koppelteken-of-trema]

Edelmanboor lijkt me dan ook logischer aangezien het correct is en analoog is aan Edelmanboring dat ook al in gebruik is op DOV.

**Comment by timothy-debock** [comment]
@ChandraAlgoe @jasper-verhaegen  wat in is dan de conclusie?

- Rollenbeitel ipv Rollebeitel

**Comment by dluts** [comment]
@timothy-debock ja over 'Rollenbeitel' hebben we consensus.

Voor 'Edelmanboor' probeer ik nog een antwoord van OVAM te pakken te krijgen.

**Comment by dluts** [comment]
@timothy-debock  ik heb met de collega's van OVAM gesproken, edelmanboor zit nog niet in hun databank. Zij zijn ook voorstander van 'Edelmanboor'.

De consensus is dus dat 'Edelmanboor' de naam is die we gaan nemen voor de code.

Gezien dat je online en in sommige projecten 'Edelman boor' ook tegenkomt stel ik voor de at deze schrijfwijze als altlabel wordt toegevoegd.
