### ISSUE TITLE
Nog 2 opties toevoegen onder Watermonsternemer

### ISSUE THREAD

**Issue by ChandraAlgoe** [bodemenondergrond/codelijst-bemonsteringsinstrument#6]
Graag Nog 2 opties toevoegen onder Watermonsternemer:
Scheppot
Kraantje

**Comment by dluts** [comment]
+1

**Comment by timothy-debock** [comment]
@ChandraAlgoe @dluts deze 2 staan toch al in de cod

**Comment by timothy-debock** [comment]
Ik zou hier toch wel voorstellen om verkleinwoorden te vermijden en 'Kraan' te zetten

**Comment by ChandraAlgoe** [comment]
akkoord @timothy-debock

**Comment by dluts** [comment]
Ja, zeer goede suggestie.
